---
- name: Docker
  ansible.builtin.import_role: { name: docker }
  vars: { docker_users: ["{{ open_webui_owner }}"] }

- name: Compose
  become: true
  become_user: "{{ open_webui_owner }}"
  vars:
    compose_dir: "{{ open_webui_compose_dir | default(bookshelf_const_compose_dir + '/open-webui', true) }}"
    conf_dir: "{{ open_webui_conf_dir }}"
    service_state: "{{ open_webui_enabled | ternary('present', 'absent') }}"
  block:
    - name: Create compose directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      loop: ["{{ compose_dir }}", "{{ conf_dir }}"]

    - name: Create compose files
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ compose_dir }}/{{ item }}"
        mode: '0600'
      loop:
        - ts-serve.json   # <- For the first 2 files order matters
        - compose.yaml
        - main.env
        - secret.env
      register: open_webui_compose_files_result

    - name: Apply service state
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: "{{ service_state }}"
        remove_orphans: true
        build: always
      register: open_webui_service_state

    - name: Restart service
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: restarted
        remove_orphans: true
      when:
        - open_webui_enabled and not open_webui_service_state.changed
        - open_webui_tailscaled and open_webui_compose_files_result.results[1].changed

- name: Mark done
  ansible.builtin.set_fact:
    open_webui_done: true
