---
# Ideas grow better together
#   https://hedgedoc.org/
# -----
# VERSIONS: https://quay.io/repository/hedgedoc/hedgedoc?tab=tags
# -----
# NOTES:
#   * container is quite restricted. See restrictions in the main.env.j2 tempate.
#     They can be overriden with extra_env
#   * with restrictions in place users registration with ./bin/manage_users tool.
# -----
hedgedoc_managed: false
hedgedoc_enabled: false
hedgedoc_version:       # Leave blank to leverage bookshelf configuration
hedgedoc_compose_dir:   # Unless you know ..., leave blank to leverage bookshelf configuration
hedgedoc_owner: "{{ ansible_facts.user_id }}"
hedgedoc_conf_dir: ~/conf/hedgedoc
hedgedoc_service_name: hedgedoc
hedgedoc_hostname: "{{ hedgedoc_service_name }}"
hedgedoc_vhost: "{{ hedgedoc_service_name }}.domain.local"
# Can disable ports if plan to access only via tailnet or reverse-proxy
hedgedoc_web_ui_port:   # Leave blank for bookshelf default, or '-1' to not expose the port
hedgedoc_tz: "{{ ansible_facts.date_time.tz | default('UTC') }}"
# HedgeDoc domain. Ex.: {{ hedgedoc_vhost }} or {{ ansible_facts.default_ipv4.address }}
hedgedoc_domain:        # (REQUIRED)
# Optional extra env vars
hedgedoc_extra_env: |    # "{{ lookup('template', playbook_dir + '/resources/hedgedoc.env.j2') }}"
  # References:
  #   * https://docs.hedgedoc.org/guides/reverse-proxy/#hedgedoc-config
  # ----------
  # CMD_URL_ADDPORT=false
  # CMD_PROTOCOL_USESSL=true
  # CMD_ALLOW_EMAIL_REGISTER=true   # <- Allow users registration
# WUD settings
hedgedoc_wudded: true    # Watched by WUD
hedgedoc_tag_rex:        # Leave blank to leverage bookshelf configuration
