---
qbittorrent_web_ui_port_int: "{{ qbittorrent_web_ui_port | default(bookshelf_const_port.qbittorrent.web_ui, true) }}"
qbittorrent_torrenting_port_int: "{{ bookshelf_const_port.qbittorrent.torrenting }}"
qbittorrent_vuetorrent_version_int: "{{ qbittorrent_vuetorrent_version | default(bookshelf_const_version.vuetorrent, true) }}"
