---
- name: Docker
  ansible.builtin.import_role: { name: docker }
  vars: { docker_users: ["{{ gatus_owner }}"] }

- name: Compose
  become: true
  become_user: "{{ gatus_owner }}"
  vars:
    compose_dir: "{{ gatus_compose_dir | default(bookshelf_const_compose_dir + '/gatus', true) }}"
    yaml_dir: "{{ compose_dir }}/config"
    conf_dir: "{{ gatus_conf_dir }}"
    service_state: "{{ gatus_enabled | ternary('present', 'absent') }}"
    the_user: "{{ ansible_facts.getent_passwd[gatus_owner] }}"
    user_uid: "{{ the_user.1 }}"
    user_gid: "{{ the_user.2 }}"
  block:
    - name: Create compose directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      loop: ["{{ compose_dir }}", "{{ yaml_dir }}", "{{ conf_dir }}/config"]

    - name: Create compose files
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ compose_dir }}/{{ item }}"
        mode: '0600'
      loop:
        - ts-serve.json   # <- Must be first
        - compose.yaml
        - main.env
        - secret.env
      register: gatus_compose_files_result

    - name: Create config files
      ansible.builtin.copy:
        content: "{{ item }}"
        dest: "{{ yaml_dir }}/{{ filename }}"
        mode: '0600'
      vars:
        # Default + User provided
        configs: "{{ (gatus_config | type_debug == 'list') | ternary(gatus_config, [gatus_config]) }}"
        filename: "config-{{ '{:03}'.format(ix + 1) }}.yaml"
      loop: "{{ configs }}"
      loop_control:
        index_var: ix
        label: "{{ filename }}"
      register: gatus_config_create_result

    - name: List all config files
      ansible.builtin.command:
        argv: [ls, -1A, "{{ yaml_dir }}"]
      changed_when: false
      register: gatus_config_current_state

    - name: Config cleanup
      ansible.builtin.file:
        path: "{{ yaml_dir }}/{{ item }}"
        state: absent
      loop: "{{ obsolete }}"
      vars:
        wanted: "{{ gatus_config_create_result.results | map(attribute='dest') | map('basename') }}"
        obsolete: "{{ gatus_config_current_state.stdout_lines | difference(wanted) | map('basename') }}"
      register: gatus_config_remove_result

    - name: Apply service state
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: "{{ service_state }}"
        remove_orphans: true
      register: gatus_service_state

    - name: Restart service
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: restarted
        remove_orphans: true
      when:
        - gatus_enabled and not gatus_service_state.changed
        - (gatus_tailscaled and gatus_compose_files_result.results[0].changed)
          or gatus_config_create_result.changed
          or gatus_config_remove_result.changed

    - name: Create note
      ansible.builtin.import_role: { name: bookshelf-note }
      # noqa: var-naming[no-role-prefix]
      vars: { src: notes.md.j2, dest: gatus-service.md, present: "{{ gatus_enabled }}" }

- name: Mark done
  ansible.builtin.set_fact:
    gatus_done: true
