---
- name: Docker
  ansible.builtin.import_role: { name: docker }
  vars: { docker_users: ["{{ opengist_owner }}"] }

- name: Compose
  become: true
  become_user: "{{ opengist_owner }}"
  vars:
    compose_dir: "{{ opengist_compose_dir | default(bookshelf_const_compose_dir + '/opengist', true) }}"
    conf_dir: "{{ opengist_conf_dir }}"
    service_state: "{{ opengist_enabled | ternary('present', 'absent') }}"
    the_user: "{{ ansible_facts.getent_passwd[opengist_owner] }}"
    user_uid: "{{ the_user.1 }}"
    user_gid: "{{ the_user.2 }}"
  block:
    - name: Create compose directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      loop: ["{{ compose_dir }}", "{{ conf_dir }}/config"]

    - name: Create compose files
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ compose_dir }}/{{ item }}"
        mode: '0600'
      loop:
        - ts-serve.json   # <- Must be first
        - compose.yaml
        - main.env
        - secret.env
      register: opengist_compose_files_result

    - name: Apply service state
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: "{{ service_state }}"
        remove_orphans: true
      register: opengist_service_state

    - name: Restart service
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: restarted
        remove_orphans: true
      when:
        - opengist_enabled and not opengist_service_state.changed
        - opengist_tailscaled and opengist_compose_files_result.results[0].changed

    - name: Create note
      ansible.builtin.import_role: { name: bookshelf-note }
      # noqa: var-naming[no-role-prefix]
      vars: { src: notes.md.j2, dest: opengist-service.md, present: "{{ opengist_enabled }}" }

- name: Mark done
  ansible.builtin.set_fact:
    opengist_done: true
