---
# Installs fancy PS1 with git PS1 suffix support. Loaded with envar.
# Doesn't require git
# -----
ps1_git_managed: false
ps1_git_users:    # <- Existing users to have this PS1
  # - "{{ ansible_facts.user_id }}"
  # - root
