---
# Desktop client for Jellyfin media server.
#   https://github.com/jellyfin/jellyfin-media-player
# -----
jellyfin_player_managed: false
jellyfin_player_starters:   # <- Existing users to have jellyfin player autostarted
  # - "{{ ansible_facts.user_id }}"
